extends: "react-app"

globals:
  __dirname: false
  graphql: false
  process: false
  TimelineLite: false
  TimelineMax: false
  TweenLite: false
  TweenMax: false

plugins:
- react-hooks

rules:
  import/first: 0
  no-use-before-define: 0
  react-hooks/rules-of-hooks: 2
  # react-hooks/reactive-deps: 2
